name: CI

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: ./
        id: test
        with:
          Auth-Token: ${{ secrets.AKAMAI_MPULSEAPITOKEN }} 
          title: ${{ github.event.repository.name }} - Build:${{ github.run_number }}
          text: ${{ github.event.head_commit.message }}
