name: CI

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: ./
        id: test
        with:
          apiToken: ${{ secrets.AKAMAI_mPulseApiToken }} 
          title: ${{ github.event.repository.name }} + "- Build:" + ${{ github.run_number }}
          text: ${{ github.event.release.tag_name }}
